[package]
name = "Kamyroll"
version = "0.2.7"
description = "A tauri app for the Kamyroll project"
authors = ["Nabil"]
license = ""
repository = ""
default-run = "Kamyroll"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.4", features = ["http-all", "shell-sidecar", "system-tray"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
